### ISSUE TITLE
Strip out comments

### ISSUE THREAD

**Issue by probablyup** [rayrutjes/jest-serializer-html#11]
First of all, love this package!

I was wondering if it would be possible to strip out HTML comments? When looking at HTML rendered by older versions of React, there's a ton of comments that end up cluttering the snapshot output.

**Comment by rayrutjes** [comment]
Yes, I think it would make sense to remove those. Comments are never used by the actual code so shouldn't be needed AFAIK.

**Comment by rayrutjes** [comment]
I went ahead with this: https://github.com/rayrutjes/diffable-html/pull/10
