### ISSUE TITLE
Should check to see if a string ends with >

### ISSUE THREAD

**Issue by phawxby** [rayrutjes/jest-serializer-html#14]
Some strings may start with < but are not actually html. An example would be http preload headers.
`<foo.svg>; rel=preload; as=image`

These get mangled as it thinks they're html.
```
<foo.css>
  ; rel=preload; as=style
</foo.css>
```

**Comment by rayrutjes** [comment]
Hey,

Thanks for opening this.

I think you are the first one encountering this use case.

If you have a solution feel free to submit a PR.

If you have actual preload headers, do you still want to format something?

**Comment by rayrutjes** [comment]
This issue was addressed in `7.0.0`.

https://github.com/rayrutjes/jest-serializer-html/pull/17
