### ISSUE TITLE
Self closing HTML tags are rendering without the closing slash

### ISSUE THREAD

**Issue by himedlooff** [rayrutjes/jest-serializer-html#29]
For example my html looks like `<img alt="" src="" />` but jest-serializer-html transforms it into `<img alt="" src="">`.

**Comment by Haroenv** [comment]
I think for that, the previous tag needs to be slightly amended on https://github.com/algolia/diffable-html/blob/master/index.js#L216 and the previous character changed from `>` to `/>`

I'm however not sure if this will be done, as `<img alt="">` is valid html, and maybe doesn't need to have the closing slash for a diffing purpose like here?

**Comment by himedlooff** [comment]
Thanks for the reply.

My use case is for Jest snapshot testing and seeing the exact HTML rendered
is important. The line breaks and indentation help readability so that's a
good trade off. Are there other transformations other than the self closing
tag that you know of?

**Comment by Haroenv** [comment]
the html is parsed and reprinted, (using htmlparser2), meaning if you want to literally check the html output and where every character counts, I wouldn't recommend this module

**Comment by himedlooff** [comment]
I'll check it out. Thank you.

**Comment by Haroenv** [comment]
I'll close this issue for now, but feel free to investigate the underlying libraries and check the differences there!
